{"uid":"2f0e8aadb6ae0e34","name":"test_02_vendor_creation_4___frugal_latido_com_np____Test_123____E___POM_for_Bottle__webapp_automation__TestData__Vendor__Sample_Data_From_Bottle_Testing__Vendor__vendor1_jpg____AT_134____Auto_Vendor_134____vendor1_mail_com___9800001028___Auomator4____Siliguri____This_is_an_Automated_generated_descriptions____Tester_4____Siliguri___9800002013___test_mail_com__","fullName":"Test_07_Vendor.TestVendors#test_02_vendor_creation_4___frugal_latido_com_np____Test_123____E___POM_for_Bottle__webapp_automation__TestData__Vendor__Sample_Data_From_Bottle_Testing__Vendor__vendor1_jpg____AT_134____Auto_Vendor_134____vendor1_mail_com___9800001028___Auomator4____Siliguri____This_is_an_Automated_generated_descriptions____Tester_4____Siliguri___9800002013___test_mail_com__","historyId":"26acbcffa281d1110ea1e88423fb8852","time":{"start":1695368224730,"stop":1695368285600,"duration":60870},"description":"Adding a new Vendor","descriptionHtml":"<p>Adding a new Vendor</p>\n","status":"broken","statusMessage":"AttributeError: 'TestVendors' object has no attribute 'log'","statusTrace":"self = <TestsCases.Test_07_Vendor.TestVendors testMethod=test_02_vendor_creation_4___frugal_latido_com_np____Test_123____E___...tor4____Siliguri____This_is_an_Automated_generated_descriptions____Tester_4____Siliguri___9800002013___test_mail_com__>\nusername = 'frugal@latido.com.np', password = 'Test@123'\nIconPath = 'E:\\\\POM_for_Bottle\\\\webapp-automation\\\\TestData\\\\Vendor\\\\Sample Data From Bottle Testing\\\\Vendor\\\\vendor1.jpg'\nvendor_id = 'AT-134', vendor_name = 'Auto_Vendor 134'\nvendor_email = 'vendor1@mail.com', vendor_phone = 9800001028\nsupply_type = 'Auomator4', location = 'Siliguri'\ndescriptions = 'This is an Automated generated descriptions'\ncontact_name = 'Tester 4', contact_location = 'Siliguri'\ncontact_number = 9800002013, contact_email = 'test@mail.com'\n\n    @allure.description(f\"Adding a new Vendor\")\n    @allure.severity(allure.severity_level.NORMAL)\n    @data(*Utils.read_xlsx(\"../TestData/Vendor/VendorData.xlsx\", \"addVendor\"))\n    @unpack\n    def test_02_vendor_creation(self, username, password, IconPath, vendor_id, vendor_name, vendor_email, vendor_phone, supply_type, location, descriptions,\n                  contact_name, contact_location, contact_number, contact_email):\n        self.LoginMethod.nativelogin(username, password)\n        try:\n>           self.assertEqual(self.vendor.addVendor(IconPath, vendor_id, vendor_name, vendor_email, vendor_phone, supply_type, location, descriptions,\n                  contact_name, contact_location, contact_number, contact_email), True, msg=\"Adding of Vendor failed!\")\n\nTest_07_Vendor.py:52: \n_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _\n\nself = <TestsCases.Test_07_Vendor.TestVendors testMethod=test_02_vendor_creation_4___frugal_latido_com_np____Test_123____E___...tor4____Siliguri____This_is_an_Automated_generated_descriptions____Tester_4____Siliguri___9800002013___test_mail_com__>\nfirst = False, second = True, msg = 'Adding of Vendor failed!'\n\n    def _patched_equals(self, first, second, msg=None):\n        try:\n>           old(self, first, second, msg)\n\nC:\\Program Files\\JetBrains\\PyCharm Community Edition 2022.3.3\\plugins\\python-ce\\helpers\\pycharm\\teamcity\\diff_tools.py:33: \n_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _\n\nself = <TestsCases.Test_07_Vendor.TestVendors testMethod=test_02_vendor_creation_4___frugal_latido_com_np____Test_123____E___...tor4____Siliguri____This_is_an_Automated_generated_descriptions____Tester_4____Siliguri___9800002013___test_mail_com__>\nfirst = False, second = True, msg = 'Adding of Vendor failed!'\n\n    def assertEqual(self, first, second, msg=None):\n        \"\"\"Fail if the two objects are unequal as determined by the '=='\n           operator.\n        \"\"\"\n        assertion_func = self._getAssertEqualityFunc(first, second)\n>       assertion_func(first, second, msg=msg)\n\nC:\\Users\\HP\\AppData\\Local\\Programs\\Python\\Python310\\lib\\unittest\\case.py:845: \n_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _\n\nself = <TestsCases.Test_07_Vendor.TestVendors testMethod=test_02_vendor_creation_4___frugal_latido_com_np____Test_123____E___...tor4____Siliguri____This_is_an_Automated_generated_descriptions____Tester_4____Siliguri___9800002013___test_mail_com__>\nfirst = False, second = True, msg = 'False != True : Adding of Vendor failed!'\n\n    def _baseAssertEqual(self, first, second, msg=None):\n        \"\"\"The default assertEqual implementation, not type specific.\"\"\"\n        if not first == second:\n            standardMsg = '%s != %s' % _common_shorten_repr(first, second)\n            msg = self._formatMessage(msg, standardMsg)\n>           raise self.failureException(msg)\nE           AssertionError: False != True : Adding of Vendor failed!\n\nC:\\Users\\HP\\AppData\\Local\\Programs\\Python\\Python310\\lib\\unittest\\case.py:838: AssertionError\n\nDuring handling of the above exception, another exception occurred:\n\nself = <TestsCases.Test_07_Vendor.TestVendors testMethod=test_02_vendor_creation_4___frugal_latido_com_np____Test_123____E___...tor4____Siliguri____This_is_an_Automated_generated_descriptions____Tester_4____Siliguri___9800002013___test_mail_com__>\nusername = 'frugal@latido.com.np', password = 'Test@123'\nIconPath = 'E:\\\\POM_for_Bottle\\\\webapp-automation\\\\TestData\\\\Vendor\\\\Sample Data From Bottle Testing\\\\Vendor\\\\vendor1.jpg'\nvendor_id = 'AT-134', vendor_name = 'Auto_Vendor 134'\nvendor_email = 'vendor1@mail.com', vendor_phone = 9800001028\nsupply_type = 'Auomator4', location = 'Siliguri'\ndescriptions = 'This is an Automated generated descriptions'\ncontact_name = 'Tester 4', contact_location = 'Siliguri'\ncontact_number = 9800002013, contact_email = 'test@mail.com'\n\n    @allure.description(f\"Adding a new Vendor\")\n    @allure.severity(allure.severity_level.NORMAL)\n    @data(*Utils.read_xlsx(\"../TestData/Vendor/VendorData.xlsx\", \"addVendor\"))\n    @unpack\n    def test_02_vendor_creation(self, username, password, IconPath, vendor_id, vendor_name, vendor_email, vendor_phone, supply_type, location, descriptions,\n                  contact_name, contact_location, contact_number, contact_email):\n        self.LoginMethod.nativelogin(username, password)\n        try:\n            self.assertEqual(self.vendor.addVendor(IconPath, vendor_id, vendor_name, vendor_email, vendor_phone, supply_type, location, descriptions,\n                  contact_name, contact_location, contact_number, contact_email), True, msg=\"Adding of Vendor failed!\")\n        except (NoSuchElementException, AssertionError, TimeoutException) as e:\n            allure.attach(self.driver.get_screenshot_as_png(), name=\"Adding of New Vendor Failed\",\n                          attachment_type=AttachmentType.PNG)\n>           self.log.error(f\"Assertion failed here while finding element.\\n {str(e)}\")\nE           AttributeError: 'TestVendors' object has no attribute 'log'\n\nTest_07_Vendor.py:57: AttributeError","flaky":false,"newFailed":false,"newBroken":false,"newPassed":false,"retriesCount":0,"retriesStatusChange":false,"beforeStages":[{"name":"_unittest_setUpClass_fixture_TestVendors","time":{"start":1695368078609,"stop":1695368078609,"duration":0},"status":"passed","steps":[],"attachments":[],"parameters":[],"stepsCount":0,"hasContent":false,"attachmentsCount":0,"shouldDisplayMessage":false}],"testStage":{"description":"Adding a new Vendor","status":"broken","statusMessage":"AttributeError: 'TestVendors' object has no attribute 'log'","statusTrace":"self = <TestsCases.Test_07_Vendor.TestVendors testMethod=test_02_vendor_creation_4___frugal_latido_com_np____Test_123____E___...tor4____Siliguri____This_is_an_Automated_generated_descriptions____Tester_4____Siliguri___9800002013___test_mail_com__>\nusername = 'frugal@latido.com.np', password = 'Test@123'\nIconPath = 'E:\\\\POM_for_Bottle\\\\webapp-automation\\\\TestData\\\\Vendor\\\\Sample Data From Bottle Testing\\\\Vendor\\\\vendor1.jpg'\nvendor_id = 'AT-134', vendor_name = 'Auto_Vendor 134'\nvendor_email = 'vendor1@mail.com', vendor_phone = 9800001028\nsupply_type = 'Auomator4', location = 'Siliguri'\ndescriptions = 'This is an Automated generated descriptions'\ncontact_name = 'Tester 4', contact_location = 'Siliguri'\ncontact_number = 9800002013, contact_email = 'test@mail.com'\n\n    @allure.description(f\"Adding a new Vendor\")\n    @allure.severity(allure.severity_level.NORMAL)\n    @data(*Utils.read_xlsx(\"../TestData/Vendor/VendorData.xlsx\", \"addVendor\"))\n    @unpack\n    def test_02_vendor_creation(self, username, password, IconPath, vendor_id, vendor_name, vendor_email, vendor_phone, supply_type, location, descriptions,\n                  contact_name, contact_location, contact_number, contact_email):\n        self.LoginMethod.nativelogin(username, password)\n        try:\n>           self.assertEqual(self.vendor.addVendor(IconPath, vendor_id, vendor_name, vendor_email, vendor_phone, supply_type, location, descriptions,\n                  contact_name, contact_location, contact_number, contact_email), True, msg=\"Adding of Vendor failed!\")\n\nTest_07_Vendor.py:52: \n_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _\n\nself = <TestsCases.Test_07_Vendor.TestVendors testMethod=test_02_vendor_creation_4___frugal_latido_com_np____Test_123____E___...tor4____Siliguri____This_is_an_Automated_generated_descriptions____Tester_4____Siliguri___9800002013___test_mail_com__>\nfirst = False, second = True, msg = 'Adding of Vendor failed!'\n\n    def _patched_equals(self, first, second, msg=None):\n        try:\n>           old(self, first, second, msg)\n\nC:\\Program Files\\JetBrains\\PyCharm Community Edition 2022.3.3\\plugins\\python-ce\\helpers\\pycharm\\teamcity\\diff_tools.py:33: \n_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _\n\nself = <TestsCases.Test_07_Vendor.TestVendors testMethod=test_02_vendor_creation_4___frugal_latido_com_np____Test_123____E___...tor4____Siliguri____This_is_an_Automated_generated_descriptions____Tester_4____Siliguri___9800002013___test_mail_com__>\nfirst = False, second = True, msg = 'Adding of Vendor failed!'\n\n    def assertEqual(self, first, second, msg=None):\n        \"\"\"Fail if the two objects are unequal as determined by the '=='\n           operator.\n        \"\"\"\n        assertion_func = self._getAssertEqualityFunc(first, second)\n>       assertion_func(first, second, msg=msg)\n\nC:\\Users\\HP\\AppData\\Local\\Programs\\Python\\Python310\\lib\\unittest\\case.py:845: \n_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _\n\nself = <TestsCases.Test_07_Vendor.TestVendors testMethod=test_02_vendor_creation_4___frugal_latido_com_np____Test_123____E___...tor4____Siliguri____This_is_an_Automated_generated_descriptions____Tester_4____Siliguri___9800002013___test_mail_com__>\nfirst = False, second = True, msg = 'False != True : Adding of Vendor failed!'\n\n    def _baseAssertEqual(self, first, second, msg=None):\n        \"\"\"The default assertEqual implementation, not type specific.\"\"\"\n        if not first == second:\n            standardMsg = '%s != %s' % _common_shorten_repr(first, second)\n            msg = self._formatMessage(msg, standardMsg)\n>           raise self.failureException(msg)\nE           AssertionError: False != True : Adding of Vendor failed!\n\nC:\\Users\\HP\\AppData\\Local\\Programs\\Python\\Python310\\lib\\unittest\\case.py:838: AssertionError\n\nDuring handling of the above exception, another exception occurred:\n\nself = <TestsCases.Test_07_Vendor.TestVendors testMethod=test_02_vendor_creation_4___frugal_latido_com_np____Test_123____E___...tor4____Siliguri____This_is_an_Automated_generated_descriptions____Tester_4____Siliguri___9800002013___test_mail_com__>\nusername = 'frugal@latido.com.np', password = 'Test@123'\nIconPath = 'E:\\\\POM_for_Bottle\\\\webapp-automation\\\\TestData\\\\Vendor\\\\Sample Data From Bottle Testing\\\\Vendor\\\\vendor1.jpg'\nvendor_id = 'AT-134', vendor_name = 'Auto_Vendor 134'\nvendor_email = 'vendor1@mail.com', vendor_phone = 9800001028\nsupply_type = 'Auomator4', location = 'Siliguri'\ndescriptions = 'This is an Automated generated descriptions'\ncontact_name = 'Tester 4', contact_location = 'Siliguri'\ncontact_number = 9800002013, contact_email = 'test@mail.com'\n\n    @allure.description(f\"Adding a new Vendor\")\n    @allure.severity(allure.severity_level.NORMAL)\n    @data(*Utils.read_xlsx(\"../TestData/Vendor/VendorData.xlsx\", \"addVendor\"))\n    @unpack\n    def test_02_vendor_creation(self, username, password, IconPath, vendor_id, vendor_name, vendor_email, vendor_phone, supply_type, location, descriptions,\n                  contact_name, contact_location, contact_number, contact_email):\n        self.LoginMethod.nativelogin(username, password)\n        try:\n            self.assertEqual(self.vendor.addVendor(IconPath, vendor_id, vendor_name, vendor_email, vendor_phone, supply_type, location, descriptions,\n                  contact_name, contact_location, contact_number, contact_email), True, msg=\"Adding of Vendor failed!\")\n        except (NoSuchElementException, AssertionError, TimeoutException) as e:\n            allure.attach(self.driver.get_screenshot_as_png(), name=\"Adding of New Vendor Failed\",\n                          attachment_type=AttachmentType.PNG)\n>           self.log.error(f\"Assertion failed here while finding element.\\n {str(e)}\")\nE           AttributeError: 'TestVendors' object has no attribute 'log'\n\nTest_07_Vendor.py:57: AttributeError","steps":[],"attachments":[{"uid":"37e28acf8987c3ad","name":"Adding of New Vendor Failed","source":"37e28acf8987c3ad.png","type":"image/png","size":91183},{"uid":"8ce5bd047ff03c3a","name":"log","source":"8ce5bd047ff03c3a.txt","type":"text/plain","size":4417}],"parameters":[],"stepsCount":0,"hasContent":true,"attachmentsCount":2,"shouldDisplayMessage":true},"afterStages":[{"name":"_unittest_setUpClass_fixture_TestVendors::0","time":{"start":1695369157203,"stop":1695369157203,"duration":0},"status":"passed","steps":[],"attachments":[],"parameters":[],"stepsCount":0,"hasContent":false,"attachmentsCount":0,"shouldDisplayMessage":false}],"labels":[{"name":"feature","value":"Inventory Dashboard"},{"name":"severity","value":"normal"},{"name":"suite","value":"Test_07_Vendor"},{"name":"subSuite","value":"TestVendors"},{"name":"host","value":"0day"},{"name":"thread","value":"9392-MainThread"},{"name":"framework","value":"pytest"},{"name":"language","value":"cpython3"},{"name":"package","value":"Test_07_Vendor"},{"name":"resultFormat","value":"allure2"}],"parameters":[],"links":[],"hidden":false,"retry":false,"extra":{"severity":"normal","retries":[],"categories":[{"name":"Test defects","matchedStatuses":[],"flaky":false}],"tags":[]},"source":"2f0e8aadb6ae0e34.json","parameterValues":[]}